import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { Order } from '../types';
import { API_BASE } from '../lib/constants';
import Layout from '../components/Layout';
import Skeleton from '../components/Skeleton';

function printPackingSlip(order: Order, items: any[]) {
  const win = window.open('', '_blank');
  if (!win) return;
  const dept = (order as any).User_Department?.Department_Name || 'Unknown';
  const staff = (order as any).Staff_Master?.Staff_Name || 'Unknown';
  win.document.write(`<!DOCTYPE html><html><head><title>Packing Slip - ${order.Order_ID}</title>
<style>body{font-family:Arial,sans-serif;padding:40px;color:#1e293b}h1{font-size:24px;margin-bottom:4px}.meta{color:#64748b;font-size:13px;margin-bottom:24px}table{width:100%;border-collapse:collapse;margin-top:16px}th,td{padding:10px 12px;text-align:left;border-bottom:1px solid #e2e8f0}th{background:#f8fafc;font-size:12px;text-transform:uppercase;color:#64748b;font-weight:700}td{font-size:14px}.total{margin-top:16px;text-align:right;font-weight:700;font-size:18px}.footer{margin-top:40px;padding-top:16px;border-top:1px solid #e2e8f0;font-size:12px;color:#94a3b8}.status{display:inline-block;padding:4px 12px;border-radius:999px;font-size:12px;font-weight:600;background:#dbeafe;color:#1d4ed8}@media print{body{padding:20px}}</style></head><body>
<h1>Packing Slip</h1>
<p class="meta">Order: ${order.Order_ID}<br>Department: ${dept}<br>Staff: ${staff}<br>Date: ${new Date(order.Order_Timestamp).toLocaleString()}<br>Status: <span class="status">${order.Order_Status}</span></p>
<table><thead><tr><th>#</th><th>Item</th><th>Qty</th></tr></thead><tbody>
${items.map((li: any, i: number) => `<tr><td>${i + 1}</td><td>${li.Inventory_Items?.Item_Name || li.Item_Name || li.Item_ID}</td><td>${li.Quantity_Requested}</td></tr>`).join('')}
</tbody></table>
<p class="total">Total Items: ${items.reduce((s: number, li: any) => s + li.Quantity_Requested, 0)}</p>
<div class="footer"><p>Generated by MediStock — ${new Date().toLocaleString()}</p></div>
<script>window.print()</script></body></html>`);
  win.document.close();
}

export default function AdminOrders() {
  const { user, token } = useAuth();
  const navigate = useNavigate();
  const [orders, setOrders] = useState<Order[]>([]);
  const [selectedOrder, setSelectedOrder] = useState<Order | null>(null);
  const [history, setHistory] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(0);
  const [total, setTotal] = useState(0);
  const PAGE_SIZE = 20;

  useEffect(() => {
    if (!user || !user.is_admin) { navigate('/'); return; }
    fetchHistory();
  }, [user, page]);

  const fetchHistory = async () => {
    try {
      const res = await fetch(`${API_BASE}/orders/history?limit=${PAGE_SIZE}&offset=${page * PAGE_SIZE}`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (data.orders) setOrders(data.orders);
      if (data.total) setTotal(data.total);
    } catch {}
    setLoading(false);
  };

  const viewOrder = async (order: Order) => {
    const res = await fetch(`${API_BASE}/orders/${order.Order_ID}`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    const data = await res.json();
    const orderWithItems = data.order || order;
    // #region agent log
    fetch('http://127.0.0.1:7938/ingest/4cc01ec9-c339-433d-bf09-8d0023db4574',{method:'POST',headers:{'Content-Type':'application/json','X-Debug-Session-Id':'55ad04'},body:JSON.stringify({sessionId:'55ad04',location:'AdminOrders.tsx:viewOrder',message:'Order detail loaded',data:{orderId:order.Order_ID,hasApiOrder:!!data.order,lineItemCount:orderWithItems.Order_Line_Items?.length??0},timestamp:Date.now(),hypothesisId:'H2'})}).catch(()=>{});
    // #endregion
    setSelectedOrder(orderWithItems);
    setHistory(data.history || []);
  };

  const getStatusInfo = (s: string) => {
    switch (s) {
      case 'Pending': return { badge: 'badge-amber', icon: '⏳' };
      case 'Packed': return { badge: 'badge-blue', icon: '📦' };
      case 'Dispatched': return { badge: 'badge-green', icon: '✅' };
      case 'Rejected': return { badge: 'badge-red', icon: '❌' };
      default: return { badge: 'badge-slate', icon: '❓' };
    }
  };

  if (!user) return null;

  return (
    <Layout title="📦 Orders" subtitle="Dispatched order history">
      {loading ? (
        <div className="space-y-3">
          <Skeleton variant="card" count={8} />
        </div>
      ) : orders.length === 0 ? (
        <div className="card p-12 text-center">
          <span className="text-5xl block mb-4">📭</span>
          <h3 className="text-lg font-bold text-slate-900 mb-1">No dispatched orders yet</h3>
          <p className="text-sm text-slate-500">Completed orders will appear here</p>
        </div>
      ) : (
        <>
          <div className="space-y-3">
            {orders.map(order => {
              const status = getStatusInfo(order.Order_Status);
              return (
                <div key={order.Order_ID} onClick={() => viewOrder(order)}
                  className="card-hover p-5 cursor-pointer">
                  <div className="flex items-center justify-between gap-4">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 bg-blue-100 rounded-xl flex items-center justify-center shrink-0">
                        <span className="text-lg">🏥</span>
                      </div>
                      <div>
                        <p className="font-bold text-slate-900">
                          {(order.User_Department as any)?.Department_Name}
                        </p>
                        <p className="text-xs text-slate-500">
                          {(order.Staff_Master as any)?.Staff_Name} · {new Date(order.Order_Timestamp).toLocaleString()}
                        </p>
                      </div>
                    </div>
                    <span className={`badge ${status.badge}`}>{status.icon} {order.Order_Status}</span>
                  </div>
                </div>
              );
            })}
          </div>
          {total > PAGE_SIZE && (
            <div className="flex justify-center items-center gap-3 mt-6">
              <button onClick={() => setPage(p => Math.max(0, p - 1))} disabled={page === 0}
                className="btn-ghost text-sm disabled:opacity-30">← Previous</button>
              <span className="text-sm text-slate-500 font-medium">Page {page + 1} of {Math.ceil(total / PAGE_SIZE)}</span>
              <button onClick={() => setPage(p => p + 1)} disabled={(page + 1) * PAGE_SIZE >= total}
                className="btn-ghost text-sm disabled:opacity-30">Next →</button>
            </div>
          )}
        </>
      )}

      {selectedOrder && (
        <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4">
          <div className="absolute inset-0 bg-black/50 backdrop-blur-sm" onClick={() => setSelectedOrder(null)} />
          <div className="relative bg-white rounded-t-3xl sm:rounded-3xl p-6 w-full max-w-lg max-h-[85vh] overflow-y-auto" role="dialog" aria-modal="true" aria-label="Order details">
            <div className="flex items-center justify-between mb-5">
              <h2 className="text-lg font-bold text-slate-900">Order Details</h2>
              <button onClick={() => setSelectedOrder(null)}
                className="w-8 h-8 rounded-lg hover:bg-slate-100 flex items-center justify-center text-slate-400" aria-label="Close details">✕</button>
            </div>
            <div className="space-y-3 mb-5">
              <div className="flex justify-between text-sm">
                <span className="text-slate-500">Department</span>
                <span className="font-semibold">{(selectedOrder.User_Department as any)?.Department_Name}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-slate-500">Staff</span>
                <span className="font-semibold">{(selectedOrder.Staff_Master as any)?.Staff_Name}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-slate-500">Time</span>
                <span className="font-semibold">{new Date(selectedOrder.Order_Timestamp).toLocaleString()}</span>
              </div>
            </div>

            {selectedOrder.Order_Line_Items && selectedOrder.Order_Line_Items.length > 0 ? (
              <div className="mb-5">
                <div className="flex items-center justify-between mb-3">
                  <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Items Ordered</p>
                  <button onClick={() => printPackingSlip(selectedOrder, selectedOrder.Order_Line_Items!)}
                    className="text-xs font-semibold text-blue-600 hover:text-blue-800">🖨 Print Slip</button>
                </div>
                <div className="space-y-2">
                  {selectedOrder.Order_Line_Items.map((li: any) => (
                    <div key={li.Line_Item_ID}
                      className="flex items-center justify-between bg-slate-50 rounded-xl px-4 py-3">
                      <span className="text-sm font-medium text-slate-700">
                        {li.Inventory_Items?.Item_Name || li.Item_Name || li.Item_ID}
                      </span>
                      <span className="badge badge-blue">×{li.Quantity_Requested}</span>
                    </div>
                  ))}
                </div>
              </div>
            ) : (
              <p className="text-sm text-slate-400 mb-5">No line items found for this order.</p>
            )}

            {history.length > 0 && (
              <div>
                <p className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-3">Previous Requests</p>
                <div className="space-y-2">
                  {history.slice(0, 5).map((h: any, i: number) => (
                    <div key={i} className="text-sm bg-slate-50 rounded-xl px-4 py-3">
                      <div className="flex items-center justify-between">
                        <span className="font-medium text-slate-700">
                          {h.Item_Name || h.Inventory_Items?.Item_Name || h.Item_ID}
                        </span>
                        <span className="badge badge-slate">×{h.Quantity_Requested}</span>
                      </div>
                      <p className="text-xs text-slate-400 mt-1">
                        {(h.Requisition_Orders as any)?.Order_Timestamp
                          ? new Date((h.Requisition_Orders as any).Order_Timestamp).toLocaleString()
                          : 'N/A'}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </Layout>
  );
}
