import { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { useToast } from '../hooks/useToast';
import { useKeyboard } from '../hooks/useKeyboard';
import { Order } from '../types';
import { API_BASE } from '../lib/constants';
import Layout from '../components/Layout';
import Skeleton from '../components/Skeleton';

function printPackingSlip(order: Order, items: any[]) {
  const win = window.open('', '_blank');
  if (!win) return;
  const dept = (order as any).User_Department?.Department_Name || 'Unknown';
  const staff = (order as any).Staff_Master?.Staff_Name || 'Unknown';
  win.document.write(`<!DOCTYPE html><html><head><title>Packing Slip - ${order.Order_ID}</title>
<style>body{font-family:Arial,sans-serif;padding:40px;color:#1e293b}h1{font-size:24px;margin-bottom:4px}.meta{color:#64748b;font-size:13px;margin-bottom:24px}table{width:100%;border-collapse:collapse;margin-top:16px}th,td{padding:10px 12px;text-align:left;border-bottom:1px solid #e2e8f0}th{background:#f8fafc;font-size:12px;text-transform:uppercase;color:#64748b;font-weight:700}td{font-size:14px}.total{margin-top:16px;text-align:right;font-weight:700;font-size:18px}.footer{margin-top:40px;padding-top:16px;border-top:1px solid #e2e8f0;font-size:12px;color:#94a3b8}.status{display:inline-block;padding:4px 12px;border-radius:999px;font-size:12px;font-weight:600;background:#dbeafe;color:#1d4ed8}@media print{body{padding:20px}}</style></head><body>
<h1>Packing Slip</h1>
<p class="meta">Order: ${order.Order_ID}<br>Department: ${dept}<br>Staff: ${staff}<br>Date: ${new Date(order.Order_Timestamp).toLocaleString()}<br>Status: <span class="status">${order.Order_Status}</span></p>
<table><thead><tr><th>#</th><th>Item</th><th>Qty</th></tr></thead><tbody>
${items.map((li: any, i: number) => `<tr><td>${i + 1}</td><td>${li.Inventory_Items?.Item_Name || li.Item_Name || li.Item_ID}</td><td>${li.Quantity_Requested}</td></tr>`).join('')}
</tbody></table>
<p class="total">Total Items: ${items.reduce((s: number, li: any) => s + li.Quantity_Requested, 0)}</p>
<div class="footer"><p>Generated by MediStock — ${new Date().toLocaleString()}</p></div>
<script>window.print()</script></body></html>`);
  win.document.close();
}

export default function AdminDashboard() {
  const { user, token } = useAuth();
  const { showToast } = useToast();
  const navigate = useNavigate();
  const [orders, setOrders] = useState<Order[]>([]);
  const [lowStockItems, setLowStockItems] = useState<any[]>([]);
  const searchInputRef = useRef<HTMLInputElement>(null);
  const [loading, setLoading] = useState(true);
  const [expandedOrder, setExpandedOrder] = useState<string | null>(null);
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [bulkStatus, setBulkStatus] = useState('');

  useKeyboard([
    { key: 'k', ctrl: true, handler: () => searchInputRef.current?.focus() },
  ], !!user);

  useEffect(() => {
    if (!user || !user.is_admin) { navigate('/'); return; }
    fetchOrders();
    fetchLowStock();
    const interval = setInterval(fetchOrders, 10000);
    return () => clearInterval(interval);
  }, [user]);

  const fetchOrders = async () => {
    try {
      const res = await fetch(`${API_BASE}/orders/pending`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (data.orders) setOrders(data.orders);
    } catch {}
    setLoading(false);
  };

  const fetchLowStock = async () => {
    try {
      const res = await fetch(`${API_BASE}/inventory/low-stock`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (data.items) setLowStockItems(data.items);
    } catch {}
  };

  const handleStatus = async (orderId: string, status: string) => {
    const res = await fetch(`${API_BASE}/orders/${orderId}/status`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
      body: JSON.stringify({ status }),
    });
    if (res.ok) { showToast(`Order ${status.toLowerCase()}`, 'success'); fetchOrders(); fetchLowStock(); }
    else { const d = await res.json(); showToast(d.error || 'Failed', 'error'); }
  };

  const handleBulk = async (status: string) => {
    if (selectedIds.size === 0) return;
    setBulkStatus(status);
    const res = await fetch(`${API_BASE}/orders/bulk-status`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
      body: JSON.stringify({ orderIds: Array.from(selectedIds), status }),
    });
    if (res.ok) { setSelectedIds(new Set()); fetchOrders(); fetchLowStock(); showToast(`${selectedIds.size} orders ${status.toLowerCase()}`, 'success'); }
    else { const d = await res.json(); showToast(d.error || 'Failed', 'error'); }
    setBulkStatus('');
  };

  const toggleSelect = (id: string) => {
    setSelectedIds(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  };

  const getTimeInfo = (timestamp: string) => {
    const mins = Math.floor((Date.now() - new Date(timestamp).getTime()) / 60000);
    if (mins < 1) return { badge: 'badge-green', text: 'Just now', urgent: false };
    if (mins < 30) return { badge: 'badge-green', text: `${mins}m ago`, urgent: false };
    if (mins < 60) return { badge: 'badge-amber', text: `${mins}m ago`, urgent: false };
    return { badge: 'badge-red', text: `${mins}m ago`, urgent: true };
  };

  const getStatusInfo = (s: string) => {
    switch (s) {
      case 'Pending': return { badge: 'badge-amber', icon: '⏳' };
      case 'Packed': return { badge: 'badge-blue', icon: '📦' };
      case 'Dispatched': return { badge: 'badge-green', icon: '✅' };
      case 'Rejected': return { badge: 'badge-red', icon: '❌' };
      default: return { badge: 'badge-slate', icon: '❓' };
    }
  };

  if (!user) return null;

  const today = new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });

  return (
    <Layout
      title="Dashboard"
      subtitle={`Good morning, ${user.name} 👋`}
      headerRight={
        <div className="flex items-center gap-2">
          <button className="btn-icon relative" aria-label="Notifications">
            🔔
            {lowStockItems.length > 0 && (
              <span className="absolute -top-0.5 -right-0.5 w-4 h-4 bg-red-500 rounded-full text-white text-[9px] font-bold flex items-center justify-center">{lowStockItems.length}</span>
            )}
          </button>
        </div>
      }
    >
      {/* Low-stock alert */}
      {lowStockItems.length > 0 && (
        <div className="bg-red-50 border border-red-200 rounded-xl p-4 flex items-center justify-between mb-6">
          <div className="flex items-center gap-2">
            <span>⚠️</span>
            <span className="text-sm font-semibold text-red-800">
              {lowStockItems.length} item{lowStockItems.length > 1 ? 's' : ''} low on stock
            </span>
          </div>
          <button onClick={() => navigate('/admin/inventory')}
            className="text-xs font-bold text-red-600 hover:text-red-800">View</button>
        </div>
      )}

      {/* Stats */}
      {loading ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-6">
          <Skeleton variant="stat-card" count={4} />
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-6">
          <div className="stat-card">
            <div className="stat-icon-box bg-amber-100">⏳</div>
            <div>
              <p className="stat-value">{orders.filter(o => o.Order_Status === 'Pending').length}</p>
              <p className="stat-label">Pending</p>
              <p className="text-xs text-slate-400 mt-0.5">Awaiting processing</p>
            </div>
          </div>
          <div className="stat-card">
            <div className="stat-icon-box bg-red-100">🔥</div>
            <div>
              <p className="stat-value text-red-600">
                {orders.filter(o => getTimeInfo(o.Order_Timestamp).urgent).length}
              </p>
              <p className="stat-label">Overdue</p>
              <p className="text-xs text-slate-400 mt-0.5">Waiting {'>'}1 hour</p>
            </div>
          </div>
          <div className="stat-card">
            <div className="stat-icon-box bg-blue-100">📦</div>
            <div>
              <p className="stat-value text-blue-600">
                {orders.filter(o => o.Order_Status === 'Packed').length}
              </p>
              <p className="stat-label">Ready</p>
              <p className="text-xs text-slate-400 mt-0.5">Packed, awaiting dispatch</p>
            </div>
          </div>
          <div className="stat-card">
            <div className="stat-icon-box bg-emerald-100">✅</div>
            <div>
              <p className="stat-value text-emerald-600">{orders.length}</p>
              <p className="stat-label">Total Active</p>
              <p className="text-xs text-slate-400 mt-0.5">All pending orders</p>
            </div>
          </div>
        </div>
      )}

      {/* Active Orders */}
      <div>
        <div className="flex items-center justify-between mb-4">
          <h2 className="section-title mb-0">Active Orders</h2>
          <div className="flex items-center gap-3">
            <div className="relative">
              <span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 text-sm">🔍</span>
              <input ref={searchInputRef} className="input pl-9 py-2 text-sm w-48" placeholder="Search orders... (Ctrl+K)" />
            </div>
            <select className="input py-2 text-sm w-32">
              <option value="all">All</option>
              <option value="Pending">Pending</option>
              <option value="Packed">Packed</option>
            </select>
            {selectedIds.size > 0 && (
              <div className="flex gap-2">
                <span className="text-xs text-slate-500 self-center font-medium">{selectedIds.size} selected</span>
                <button onClick={() => handleBulk('Packed')} disabled={!!bulkStatus}
                  className="btn-primary text-xs py-1.5 px-3">{bulkStatus === 'Packed' ? '...' : '📦 Pack All'}</button>
                <button onClick={() => handleBulk('Rejected')} disabled={!!bulkStatus}
                  className="btn-danger text-xs py-1.5 px-3">{bulkStatus === 'Rejected' ? '...' : '✕ Reject All'}</button>
              </div>
            )}
          </div>
        </div>

        {loading ? (
          <div className="space-y-3">
            <Skeleton variant="card" count={5} />
          </div>
        ) : orders.length === 0 ? (
          <div className="card p-12 text-center">
            <span className="text-5xl block mb-4">📭</span>
            <h3 className="text-lg font-bold text-slate-900 mb-1">No pending orders</h3>
            <p className="text-sm text-slate-500">New requisitions will appear here in real-time</p>
          </div>
        ) : (
          <div className="space-y-3">
            {orders.map(order => {
              const time = getTimeInfo(order.Order_Timestamp);
              const status = getStatusInfo(order.Order_Status);
              const isExpanded = expandedOrder === order.Order_ID;
              const isSelected = selectedIds.has(order.Order_ID);

              return (
                <div key={order.Order_ID}
                  className={`order-card ${time.urgent ? 'urgent' : ''} ${isSelected ? 'ring-2 ring-blue-400' : ''}`}>
                  <div className="p-5">
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex items-center gap-3">
                        <input type="checkbox" checked={isSelected}
                          onChange={() => toggleSelect(order.Order_ID)}
                          className="w-4 h-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500 mt-1" aria-label={`Select order ${order.Order_ID}`} />
                        <div className="w-10 h-10 bg-blue-100 rounded-xl flex items-center justify-center shrink-0">
                          <span className="text-lg">🏥</span>
                        </div>
                        <div>
                          <p className="font-bold text-slate-900">
                            {(order.User_Department as any)?.Department_Name || 'Unknown'}
                          </p>
                          <p className="text-xs text-slate-500">
                            by {(order.Staff_Master as any)?.Staff_Name || 'Unknown'}
                            <span className="mx-1.5">·</span>
                            ID: {order.Staff_ID}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <span className={`badge ${time.badge}`}>{time.text}</span>
                        <span className={`badge ${status.badge}`}>{status.icon} {order.Order_Status}</span>
                      </div>
                    </div>

                    <button onClick={() => setExpandedOrder(isExpanded ? null : order.Order_ID)}
                      className="mt-3 ml-7 text-xs font-semibold text-blue-600 hover:text-blue-700" aria-expanded={isExpanded}>
                      {isExpanded ? '▲ Hide Items' : '▼ View Items'}
                    </button>

                    {isExpanded && order.Order_Line_Items && order.Order_Line_Items.length > 0 && (
                      <div className="mt-3 ml-7 bg-slate-50 rounded-xl p-3 space-y-2">
                        <div className="flex items-center justify-between mb-2">
                          <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Ordered Items</p>
                          <button onClick={() => printPackingSlip(order, order.Order_Line_Items!)}
                            className="text-xs font-semibold text-blue-600 hover:text-blue-800">🖨 Print Slip</button>
                        </div>
                        {order.Order_Line_Items.map((item: any) => (
                          <div key={item.Line_Item_ID}
                            className="flex items-center justify-between bg-white rounded-lg px-3 py-2">
                            <span className="text-sm font-medium text-slate-700">
                              {item.Inventory_Items?.Item_Name || item.Item_Name || item.Item_ID}
                            </span>
                            <span className="badge badge-blue">×{item.Quantity_Requested}</span>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                  <div className="border-t border-slate-100 px-5 py-4 bg-slate-50/50 flex gap-2">
                    {order.Order_Status === 'Pending' && (
                      <button onClick={() => handleStatus(order.Order_ID, 'Packed')}
                        className="flex-1 btn-primary text-sm py-2.5">📦 Pack Order</button>
                    )}
                    {order.Order_Status === 'Packed' && (
                      <button onClick={() => handleStatus(order.Order_ID, 'Dispatched')}
                        className="flex-1 btn-success text-sm py-2.5">✅ Confirm Dispatch</button>
                    )}
                    <button onClick={() => handleStatus(order.Order_ID, 'Rejected')}
                      className="btn-danger text-sm py-2.5 px-4">✕ Reject</button>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </Layout>
  );
}
